export const SKIP_QUESTION = "SKIP_QUESTION";
export const SAVE_AND_NEXT_QUESTION = "SAVE_AND_NEXT_QUESTION";
export const SAVE_AND_SUBMIT = "SAVE_AND_SUBMIT";
export const LOAD_DATA = "LOAD_DATA";
export const SAVE_USER_DETAIL = "SAVE_USER_DETAIL";